### ISSUE TITLE
Where is AdministrativeAccess?

### ISSUE THREAD

**Issue by Yen168** [awsdocs/aws-deeplens-user-guide#3]
Can not find AdministrativeAccess but AdministratorAccess in IAM Mgt console....

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
