### ISSUE TITLE
Using DeepLens to record video clips

### ISSUE THREAD

**Issue by sophia-wright-blue** [awsdocs/aws-deeplens-user-guide#5]
Hello,

I have DeepLens all set up and am able to view the stream on a monitor. I'd like to use DeepLens to record short video clips (before I run inference on them). I'd like to get people to come in front of the camera one by one, perform some action (like sit, jump..), and I'd like to record 3-5 second clips (in mp4 or avi format) of each action. What is the easiest way of doing this? 

Thanks,

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
