### ISSUE TITLE
Links to S3 files are AccessDenied

### ISSUE THREAD

**Issue by wparad** [awsdocs/aws-deeplens-user-guide#9]
[https://s3.amazonaws.com/deeplens-public/factory-restore/Ubuntu-Live-16.04.3-Recovery.iso](https://s3.amazonaws.com/deeplens-public/factory-restore/Ubuntu-Live-16.04.3-Recovery.iso)

![image](https://user-images.githubusercontent.com/5056218/114910601-607dd980-9e1e-11eb-8169-e6b611871ce1.png)

[https://s3.amazonaws.com/deeplens-public/factory-restore/DeepLensFactoryRestore.zip](https://s3.amazonaws.com/deeplens-public/factory-restore/DeepLensFactoryRestore.zip)

![image](https://user-images.githubusercontent.com/5056218/114910685-7c817b00-9e1e-11eb-80fe-39b31d2778dd.png)

**Comment by drentin** [comment]
I am receiving the same errors so this is just not something at your end.

**Comment by CloudMisFit** [comment]
It has been 2 months and still no updates??

**Comment by drentin** [comment]
I'm happy to report that the exisiting links are working again and I have successfully reset my 1.0 device back to the factory settings and it is working again 😀

**Comment by froggie901** [comment]
Thank you for creating this issue, a member of the team has resolved the issue and the links are working.
